# 查看具体配置文档 https://github.com/lowlighter/metrics/blob/master/action.yml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: GitHub metrics
on:
  schedule: 
      - cron: "* */12 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: metrics_01
        uses: lowlighter/metrics@latest
        with:
          filename: ./assets/metrics_01.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: sun0225SUN
          template: classic
          base: "header, activity, community, repositories, metadata"
          
      - name: metrics_02
        uses: lowlighter/metrics@latest
        with:
          filename: ./assets/metrics_02.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: sun0225SUN
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 3
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 3
          plugin_stars: yes
          plugin_stars_limit: 3
